config/routes.rb
Atlrug::Application.routes.draw do
  root to: 'content#index'

  get '/meetings' => 'content#meetings'
  get '/videos' => 'content#videos'
  get '/hire' => 'content#hire'
  get '/learn' => 'content#learn'
  get '/community' => 'content#community'
  get '/job' => 'content#job'

  resources :talks, only: [:new, :create] do
    get :approve, on: :collection
    put :accept, on: :member
  end

  resources :jobs, only: [:index, :new, :create] do
    get :view, on: :member
    get :delete, on: :member
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/login' => redirect('/auth/github'), :as => :login
  get '/log_out' => 'sessions#destroy', :as => :log_out

  get '/youtube', to: redirect('https://www.youtube.com/playlist?list=PLqZY2tk6rSRn2Vapk2raOTFjXGiDbpQUU')

end

app/views/layouts/_banner.html.haml
#banner-wrapper
	#banner
		.container
			.row
				.col-md-12
					.col-md-7
						%h1 Atlanta Ruby Users Group
					.col-md-7
						%h4 Meet with others interested in developing, promoting, fostering, strengthening, and improving the Ruby programming language and Ruby community.

app/views/layouts/_footer.html.haml
#sponsors.container
  .row
    .col-md-7
      %h4 <b>Platinum Sponsors
      %ul.platinum
        %li
          %a{:href => 'http://www.pardot.com'} Pardot
          – B2B Marketing Automation
        %li.sponsor-image
          %a{:href => 'http://www.pardot.com'}
            =image_tag "pardot-logo.png", :alt => 'Pardot'
      %ul.platinum
        %li
          %a{:href => 'http://mandrill.com'} Mandrill
          – Transactional Email from MailChimp
        %li.sponsor-image
          %a{:href => 'http://mandrill.com'}
            =image_tag "mandrill.png", :alt => 'Mandrill'

app/views/layouts/_footerlinks.html.haml
#contact-us.container
  .row
    .col-md-8
      %ul.nav
        %li.active
          %a{:href => "http://meetup.com/atlantaruby/"}
            %i.icon-group
            Meetup
        %li
          %a{:href => "http://twitter.com/atlrug"}
            %i.icon-twitter
            @atlrug
        %li
          %a{:href => "https://github.com/atlrug/atlrug/wiki"}
            %i.icon-github
            Wiki
        %li
          %a{:href => "http://www.linkedin.com/groups/Atlanta-Ruby-Users-Group-106945/about"}
            %i.icon-linkedin-sign
            Linkedin
        %li
          %a{:href => "https://tech404.slack.com/messages/rails"}
            %i.icon-comments-alt
            Slack/Tech404/Rails
        %li
          %a{:href => "https://github.com/atlrug/CoC"}
            %i.icon-file-alt
            Code of Conduct

app/views/layouts/_navbar.html.haml
#main-nav.navbar
  .navbar-inner
    .container
      %a{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :class => "btn navbar-btn"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

      %a.logo{:href => root_url }
        =image_tag "ATLRUG_logo.png", :alt => 'Atlanta Ruby Logo'
      %div.navbar-collapse
        %ul.nav.navbar-nav.nav-links.navbar-left
          %li
            = link_to 'Go to Meetings', meetings_path
          %li
            = link_to 'Find Presentations', videos_path
        %ul.nav.navbar-nav.nav-links.navbar-right
          %li
            = link_to 'Community', '/community'
          %li
            = link_to 'Learn Ruby', '/learn'
          %li
            = link_to 'Find a Job', jobs_path

app/views/layouts/application.html.haml
%html
  %head
    %title Atlanta Ruby Users' Group

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = stylesheet_link_tag    "http://fonts.googleapis.com/css?family=Roboto+Slab:400,700"
    = stylesheet_link_tag    "//netdna.bootstrapcdn.com/font-awesome/3.1.1/css/font-awesome.css"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tag

  %body
    = render 'layouts/navbar'
    #main= yield
    / #tweet
    /   %a{:href=>"http://twitter.com/atlrug", :class=> "twitter-follow-button", :'data-show-count'=> "false"} Follow @atlrug
    /   %script{:src=> "http://platform.twitter.com/widgets.js", :type=>"text/javascript"}
    / #sidebar

    #footer
      = render 'layouts/footer'
    #footer-links
      = render 'layouts/footerlinks'